package main

import (
	"fmt"
	"os"
	"strings"
	"text/template"
)

func main() {
	fmt.Println("package metrics")
	fmt.Println()
	fmt.Println("// generated by `go run ./gen_defs > defs_generated.go && gofmt -w defs_generated.go`")
	fmt.Println()

	type vars struct {
		N           int
		Ns          []int
		Metric      string
		MetricLower string
	}

	n := 6
	ns := make([]int, n)
	for j := range ns {
		ns[j] = j
	}

	for _, metric := range []string{"Counter", "Gauge"} {
		for i := 2; i < n; i++ {
			counterGaugeTmpl.Execute(os.Stdout, vars{
				N:           i,
				Ns:          ns[:i],
				Metric:      metric,
				MetricLower: strings.ToLower(metric),
			})

			for k := 1; k <= i-1; k++ {
				bindPrefixTmpl.Execute(os.Stdout, struct {
					N        int
					Ns       []int
					K        int
					Ks       []int
					NMinusK  int
					NMinusKs []int
					Metric   string
				}{
					N:        i,
					Ns:       ns[:i],
					K:        k,
					Ks:       ns[:k],
					NMinusK:  i - k,
					NMinusKs: ns[k:i],
					Metric:   metric,
				})
			}
		}
	}
	for _, metric := range []string{"Histogram", "Distribution"} {
		for i := 2; i < n; i++ {
			histogramDistributionTmpl.Execute(os.Stdout, vars{
				N:           i,
				Ns:          ns[:i],
				Metric:      metric,
				MetricLower: strings.ToLower(metric),
			})
		}
	}

	for i := 2; i < n; i++ {
		setTmpl.Execute(os.Stdout, vars{
			N:           i,
			Ns:          ns[:i],
			Metric:      "Set",
			MetricLower: "set",
		})
	}
}

var counterGaugeTmpl = template.Must(template.New("name").Parse(`
type {{.Metric}}Def{{.N}}[{{range .Ns}} V{{.}} TagValue, {{end}}] struct {
	name   string
	prefix []string
	keys   [{{.N}}]string
	ok     bool
}

func New{{.Metric}}Def{{.N}}[{{range .Ns}} V{{.}} TagValue, {{end}}](
	name string,
	description string,
	unit Unit,
	keys [{{.N}}]string,
) *{{.Metric}}Def{{.N}}[{{range .Ns}} V{{.}}, {{end}}] {
	ok := registerDef({{.MetricLower}}Type, name, unit, description)
	return &{{.Metric}}Def{{.N}}[{{range .Ns}} V{{.}}, {{end}}]{
		name: name,
		keys: keys,
		ok:   ok,
	}
}

func (d *{{.Metric}}Def{{.N}}[{{range .Ns}} V{{.}}, {{end}}]) Values({{range .Ns}}v{{.}} V{{.}}, {{end}}) *{{.Metric}}Def {
	return &{{.Metric}}Def{
		name: d.name,
		tags: joinStrings(d.prefix, []string{
			{{range .Ns}}
			makeTag(d.keys[{{.}}], tagValueString(v{{.}})),
			{{ end }}
		}),
		ok: d.ok,
	}
}
`))

var histogramDistributionTmpl = template.Must(template.New("name").Parse(`
type {{.Metric}}Def{{.N}}[{{range .Ns}} V{{.}} TagValue, {{end}}] struct {
	name       string
	keys       [{{.N}}]string
	sampleRate float64
	ok         bool
}

func New{{.Metric}}Def{{.N}}[{{range .Ns}} V{{.}} TagValue, {{end}}](
	name string,
	description string,
	unit Unit,
	keys [{{.N}}]string,
	sampleRate float64,
) *{{.Metric}}Def{{.N}}[{{range .Ns}} V{{.}}, {{end}}] {
	ok := registerDef({{.MetricLower}}Type, name, unit, description)
	return &{{.Metric}}Def{{.N}}[{{range .Ns}} V{{.}}, {{end}}]{
		name:       name,
		keys:       keys,
		sampleRate: sampleRate,
		ok:         ok,
	}
}

func (d *{{.Metric}}Def{{.N}}[{{range .Ns}} V{{.}}, {{end}}]) Values({{range .Ns}} v{{.}} V{{.}}, {{end}}) *{{.Metric}}Def {
	return &{{.Metric}}Def{
		name: d.name,
		tags: []string{
			{{range .Ns}}
			makeTag(d.keys[{{.}}], tagValueString(v{{.}})),
			{{ end }}
		},
		sampleRate: d.sampleRate,
		ok: d.ok,
	}
}
`))

var setTmpl = template.Must(template.New("name").Parse(`
type {{.Metric}}Def{{.N}}[{{range .Ns}} V{{.}} TagValue, {{end}}] struct {
	name       string
	keys       [{{.N}}]string
	sampleRate float64
	ok         bool
}

func New{{.Metric}}Def{{.N}}[{{range .Ns}} V{{.}} TagValue, {{end}}](
	name string,
	description string,
	unit Unit,
	keys [{{.N}}]string,
	sampleRate float64,
) *{{.Metric}}Def{{.N}}[{{range .Ns}} V{{.}}, {{end}}] {
	ok := registerDef({{.MetricLower}}Type, name, unit, description)
	return &{{.Metric}}Def{{.N}}[{{range .Ns}} V{{.}}, {{end}}]{
		name:       name,
		keys:       keys,
		sampleRate: sampleRate,
		ok:         ok,
	}
}

func (d *{{.Metric}}Def{{.N}}[{{range .Ns}} V{{.}}, {{end}}]) Values({{range .Ns}} v{{.}} V{{.}}, {{end}}) *{{.Metric}}Def {
	return &{{.Metric}}Def{
		name: d.name,
		tags: []string{
			{{range .Ns}}
			makeTag(d.keys[{{.}}], tagValueString(v{{.}})),
			{{ end }}
		},
		sampleRate: d.sampleRate,
		ok:         d.ok,
	}
}
`))

var bindPrefixTmpl = template.Must(template.New("name").Parse(`
// Prefix{{.K}} sets the value of the first {{.K}} tags, returning a {{.Metric}}Def{{.NMinusK}} that
// can be used to set the rest.
func (d *{{.Metric}}Def{{.N}}[{{range .Ns}} V{{.}}, {{end}}]) Prefix{{.K}}({{range .Ks}} v{{.}} V{{.}}, {{end}}) *{{.Metric}}Def{{.NMinusK}}[{{range .NMinusKs}} V{{.}}, {{end}}] {
	return &{{.Metric}}Def{{.NMinusK}}[{{range .NMinusKs}} V{{.}}, {{end}}]{
		name: d.name,
		prefix: []string{
			{{range .Ks}}
			makeTag(d.keys[{{.}}], tagValueString(v{{.}})),
			{{ end }}
		},
		keys: *((*[{{.NMinusK}}]string)(d.keys[{{.K}}:])),
		ok:   d.ok,
	}
}
`))
